### ISSUE TITLE
build error ubuntu rust 1.28.0

### ISSUE THREAD

**Issue by RCasatta** [iSma/timv#1]
error[E0599]: no method named `get_pixel` found for type `image::DynamicImage` in the current scope
  --> src/pixelize.rs:15:20
   |
15 |              image.get_pixel(x*2, y*2).data,
   |                    ^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
           `use image::GenericImageView;`

error[E0599]: no method named `get_pixel` found for type `image::DynamicImage` in the current scope
  --> src/pixelize.rs:16:20
   |
16 |              image.get_pixel(x*2+1, y*2).data,
   |                    ^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
           `use image::GenericImageView;`

error[E0599]: no method named `get_pixel` found for type `image::DynamicImage` in the current scope
  --> src/pixelize.rs:17:20
   |
17 |              image.get_pixel(x*2, y*2+1).data,
   |                    ^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
           `use image::GenericImageView;`

error[E0599]: no method named `get_pixel` found for type `image::DynamicImage` in the current scope
  --> src/pixelize.rs:18:20
   |
18 |              image.get_pixel(x*2+1, y*2+1).data,
   |                    ^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
           `use image::GenericImageView;`

error[E0599]: no method named `dimensions` found for type `&image::DynamicImage` in the current scope
  --> src/pixelize.rs:35:36
   |
35 |     let (image_w, image_h) = image.dimensions();
   |                                    ^^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
           `use image::GenericImageView;`

error: aborting due to 5 previous errors

For more information about this error, try `rustc --explain E0599`.
error: Could not compile `timv`.

**Comment by iSma** [comment]
Fixed with the latest commit. Thanks for the info.
